services:
  coffee-database:
    image: postgres:alpine
    container_name: final-database
    ports:
      - "6004:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: final